### ISSUE TITLE
'pogreb' has connotations of death

### ISSUE THREAD

**Issue by 0joshuaolson1** [akrylysov/pogreb#10]
https://en.wiktionary.org/wiki/pogreb

**Comment by akrylysov** [comment]
Thanks for letting me know, In Russian and Ukrainian it means "cellar".

**Comment by 0joshuaolson1** [comment]
Which is remarkably similar, admittedly.

**Comment by akrylysov** [comment]
While both meanings have some similarities, in Russian "pogreb" means a place to store vegetable, pickles and other food (see https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%B3%D1%80%D0%B5%D0%B1) which doesn't have connotations of death. In my opinion, the project name is ok as long it doesn't mean anything inappropriate in the English language.

**Comment by mvrhov** [comment]
Well in Slovenian and probably some other slovanic language it means a funeral.
