### ISSUE TITLE
Document MaxKeys and workaround?

### ISSUE THREAD

**Issue by 0joshuaolson1** [akrylysov/pogreb#11]
[`1 << 30`](https://github.com/akrylysov/pogreb/blob/af295d0772e15c0b2adf7b5a57596d5872c9c581/db.go#L27) is 1 073 741 824, a fourth of the range of a `uint32`. One can't necessarily just make more `db` files (assuming the hash function is available to direct to the right database) because different operating systems have different file/inode limits and open file descriptor limits.

A related question is why this limit. I don't see how it'd be related to density because keys are arrays of *any* size. Is a file bigger than a terabyte outside the intended use cases?

**Comment by 0joshuaolson1** [comment]
Hm... file size limits (depending on OS, not storage) also enter the design space of intended use, which I'm hoping [future documentation](https://github.com/akrylysov/pogreb/issues/7#issuecomment-373960258) will address.

**Comment by akrylysov** [comment]
I set the `MaxKeys` value to `math.MaxUint32` (https://github.com/akrylysov/pogreb/commit/b08c0bfa1afc981852b0c16c2b38d4284d4b1f04). I don't have plans of making the value larger than `MaxUint32` right now, it would require storing 64-bit hashes. `MaxKeys` was already documented https://godoc.org/github.com/akrylysov/pogreb#pkg-constants.
