### ISSUE TITLE
Are the metrics optimized out if unused?

### ISSUE THREAD

**Issue by 0joshuaolson1** [akrylysov/pogreb#14]
I don't suppose you or someone would know the answer to this for the latest Go compilers? (version 1.10 at time of comment and assuming a GCC 8 release soon)

Idea: make such things configurable...

**Comment by akrylysov** [comment]
The metrics can't be optimized out because they are used by the `startSyncer` function (https://github.com/akrylysov/pogreb/blob/master/db.go#L131).

**Comment by 0joshuaolson1** [comment]
That's what I feared. Thanks!
