### ISSUE TITLE
Question about your loops

### ISSUE THREAD

**Issue by wade-welles** [akrylysov/pogreb#17]
Hello, nice to meet you, I was experimenting with your library and I noticed a few things in my review but one thing jumped out and I felt it would be worth bringing up to you. 

You decided to do your loops like this:

```go
for i := 0; i < slotsPerBucket; i++ {
		_ = data[18] // bounds check hint to compiler; see golang.org/issue/14808
		b.slots[i].hash = binary.LittleEndian.Uint32(data[:4])
		b.slots[i].keySize = binary.LittleEndian.Uint16(data[4:6])
		b.slots[i].valueSize = binary.LittleEndian.Uint32(data[6:10])
		b.slots[i].kvOffset = int64(binary.LittleEndian.Uint64(data[10:18]))
		data = data[18:]
}
```

Which is a bit more of a Java or C style. And you could have done it like this:

```go
for _, slot := range b.slots {
		_ = data[18] // bounds check hint to compiler; see golang.org/issue/14808
		slot.hash = binary.LittleEndian.Uint32(data[:4])
		slot.keySize = binary.LittleEndian.Uint16(data[4:6])
		slot.valueSize = binary.LittleEndian.Uint32(data[6:10])
		slot.kvOffset = int64(binary.LittleEndian.Uint64(data[10:18]))
		data = data[18:]
}
```

I would put forth that it is a bit more than just an aesthetic choice, it becomes both more readable and more manageable. And this could be done throughout your code to reduce the overall footprint a fair size. 

I didn't want to create a pull request until I began a discussion regarding the topic in-case there was something I was overlooking and you had a specific reason for this choice.

**Comment by akrylysov** [comment]
Hi! The range loop returns copies of the items so the code has to use array indexes to modify the values. Take a look at the following example, it doesn't update the array items:
```go
b := bucket{}
for _, slot := range b.slots {
    slot.hash = 1
}
fmt.Println(b)
```

**Comment by wade-welles** [comment]
Thank you, I see now, so you either have to index, rewrite the function without making a copy of the slice, or use pointers. And I agree that out of those choices you made the best one. Thanks for taking the time to clarify.

**Comment by wade-welles** [comment]
dw
