### ISSUE TITLE
Open/read does not fail on invalid file

### ISSUE THREAD

**Issue by dsoprea** [akrylysov/pogreb#18]
Recently I realized I was opening the wrong database and it took me an hour to figure it out because `(*DB).FileSize()` was returning non-zero and `(*DB).Count()` was returning zero, and there were no errors reported by `(*DB).Open()`. We have no standard way to figure out if the DB is invalid?

As a bonus, doing this will also change the target file even if it wasn't a correct/working database file to begin with.

**Comment by akrylysov** [comment]
Interesting, pogreb checks the file header when it opens the database file (https://github.com/akrylysov/pogreb/blob/master/db.go#L193), but it does it only for the index. I'll add an additional check, thanks for the report!

**Comment by dsoprea** [comment]
Your project had yet to be exposed to the right class of moron, and I'm here to help.

**Comment by akrylysov** [comment]
The issue was fixed in https://github.com/akrylysov/pogreb/commit/3108cc9bb403099656d1b6f8fa7b236ec04f034e, thanks for the bug report!
