### ISSUE TITLE
Please share Write benchmark as well

### ISSUE THREAD

**Issue by rebootcode** [akrylysov/pogreb#19]
Hi, Can you also share write performance benchmark against badger, bolt and other as provided for `read`?

**Comment by akrylysov** [comment]
You can find the benchmarking tool at https://github.com/akrylysov/pogreb-bench it measure the write and read performance for pogreb, goleveldb, bbolt and badger.

**Comment by xchz** [comment]
Choosing the right data structure and optimizing the store for the specific use case (random lookups) allowed to make Pogreb significantly faster than similar solutions.
