### ISSUE TITLE
Documentation Clarification: Rebuilding Daily

### ISSUE THREAD

**Issue by AusIV** [akrylysov/pogreb#26]
In the documentation, you say:

> I needed to rebuild the mapping once a day and then access it in read-only mode.

From this it makes me wonder whether pogreb is intended to be used that way, or if it was intended to solve the problem of having to do that.

**Comment by akrylysov** [comment]
Pogreb was created with a single use case in mind - building entirely new database once a day and accessing in it read-only mode after. That was the requirement of the project it was built for, but you don't have to use it this way.

**Comment by akrylysov** [comment]
Updated design document https://github.com/akrylysov/pogreb/blob/master/docs/design.md.
