### ISSUE TITLE
panic after restart

### ISSUE THREAD

**Issue by remotejob** [akrylysov/pogreb#27]
After restart 

`panic: runtime error: slice bounds out of range [:8511984455920089209] with capacity 1073741824

goroutine 1 [running]:
github.com/akrylysov/pogreb/fs.(*osfile).Slice(0xc0002ea3f0, 0x7620a4c3a4c37679, 0x7620a4c3a4c37879, 0xc0000b7b58, 0xc0000b7af8, 0xc0000b7b48, 0xc0009a9340, 0xc0000b7b50)
        /exwindoz/home/juno/gowork/pkg/mod/github.com/akrylysov/pogreb@v0.8.3/fs/os.go:68 +0xa8
github.com/akrylysov/pogreb.(*bucketHandle).read(0xc0000b77d8, 0x20616c6c, 0x20616c6c61766174)
        /exwindoz/home/juno/gowork/pkg/mod/github.com/akrylysov/pogreb@v0.8.3/bucket.go:76 +0x56
github.com/akrylysov/pogreb.(*DB).forEachBucket(0xc0002f01a0, 0xc000000009, 0xc0000b7b58, 0x8928a1, 0x419b36)
        /exwindoz/home/juno/gowork/pkg/mod/github.com/akrylysov/pogreb@v0.8.3/db.go:178 +0xc4
github.com/akrylysov/pogreb.(*DB).put(0xc0002f01a0, 0x9d3cc9e9, 0xc00039c4b0, 0x10, 0x10, 0xc00068f000, 0x2927, 0x4b09, 0x0, 0x0)
        /exwindoz/home/juno/gowork/pkg/mod/github.com/akrylysov/pogreb@v0.8.3/db.go:384 +0x161
github.com/akrylysov/pogreb.(*DB).Put(0xc0002f01a0, 0xc00039c4b0, 0x10, 0x10, 0xc00068f000, 0x2927, 0x4b09, 0x0, 0x0)
        /exwindoz/home/juno/gowork/pkg/mod/github.com/akrylysov/pogreb@v0.8.3/db.go:366 +0x16a
gitlab.com/remotejob/mlfactory-feederv4/pkg/pogrebhandler.InsertAllQue(0xc0001481c0, 0xc000586000, 0x63, 0x80, 0xc000aae000, 0x9c4)
        /exwindoz/home/juno/gowork/src/gitlab.com/remotejob/mlfactory-feederv4/pkg/pogrebhandler/pogrebhandler.go:25 +0x14e
main.main()
        /exwindoz/home/juno/gowork/src/gitlab.com/remotejob/mlfactory-feederv4/cmd/rpcfeeder/main.go:274 +0x456
exit status 2`

**Comment by akrylysov** [comment]
hi! can you provide steps how to reproduce the issue?

**Comment by remotejob** [comment]
Looks like db need Close() in my case it's long time service sometimes I need restart by 
 systemctl restart nlpfeeder.service, I start all config in config.go so I can't use defer.
I added  Graceful Shutdown. Looks like it help.

`	stop := make(chan os.Signal)
	signal.Notify(stop, syscall.SIGTERM, syscall.SIGINT)

go func() {
		defer signal.Stop(stop)
		sig := <-stop
		log.Println(sig.String())
		**conf.PogrebDB.Close()**
	}()`

speed seems not bad!!

**Comment by akrylysov** [comment]
Thanks, the database must be closed after use by calling `Close`. It shouldn't panic even if it wasn't closed properly. I'll investigate the issue.

**Comment by remotejob** [comment]
How make count records function ? Is it correct ?
`func CountPages(conf *config.Config) (int, error) {

	var res int

	it := conf.PogrebDB.Items()
	for {
		_, _, err := it.Next()
		if err != nil {
			if err != pogreb.ErrIterationDone {
				// log.Fatal(err)
				return 0, err
			}
			break
		}

		res = res + 1

	}

	return res, nil

}`

**Comment by akrylysov** [comment]
> How make count records function ?

There is `Count` method https://godoc.org/github.com/akrylysov/pogreb#DB.Count.

**Comment by remotejob** [comment]
Thanks.
My test:
`func main() {
	dbp, err := pogreb.Open("pogreb", nil)
	if err != nil {
		log.Fatal(err)
	}
	defer dbp.Close()

	log.Println("count", dbp.Count())
}`

OK

`
func main() {
	dbp, err := pogreb.Open("pogreb", nil)
	if err != nil {
		log.Fatal(err)
	}
	//defer dbp.Close()

	log.Println("count", dbp.Count())
}
`
Damage DB

**Comment by remotejob** [comment]
I try use pogreb in quite intensive project (read,write,delete)

But quite often it's crack always I have


`panic: runtime error: slice bounds out of range [:8260942477082797763] with capacity 1160943104

goroutine 1 [running]:
github.com/akrylysov/pogreb/fs.(*osfile).Slice(0xc0001870e0, 0x72a4c36a2074a4c3, 0x72a4c36a2074a6c3, 0xc000101c00, 0xc000101ba0, 0xc000101bf0, 0xc00008a000, 0xc000101bf8)
        /exwindoz/home/juno/gowork/pkg/mod/github.com/akrylysov/pogreb@v0.8.3/fs/os.go:68 +0xa8
github.com/akrylysov/pogreb.(*bucketHandle).read(0xc000101880, 0xa4c37420, 0x6e206ea4c3a4c36e)
        /exwindoz/home/juno/gowork/pkg/mod/github.com/akrylysov/pogreb@v0.8.3/bucket.go:76 +0x56
github.com/akrylysov/pogreb.(*DB).forEachBucket(0xc000188a90, 0xc000001592, 0xc000101c00, 0x894171, 0x419b36)
        /exwindoz/home/juno/gowork/pkg/mod/github.com/akrylysov/pogreb@v0.8.3/db.go:178 +0xc4
github.com/akrylysov/pogreb.(*DB).put(0xc000188a90, 0x5c9e3592, 0xc00028d9e0, 0x10, 0x10, 0xc0006d2a80, 0x2724, 0x49c8, 0x0, 0x0)
        /exwindoz/home/juno/gowork/pkg/mod/github.com/akrylysov/pogreb@v0.8.3/db.go:384 +0x161
github.com/akrylysov/pogreb.(*DB).Put(0xc000188a90, 0xc00028d9e0, 0x10, 0x10, 0xc0006d2a80, 0x2724, 0x49c8, 0x0, 0x0)
        /exwindoz/home/juno/gowork/pkg/mod/github.com/akrylysov/pogreb@v0.8.3/db.go:366 +0x16a
` 

And DB broken not usable any more

**Comment by akrylysov** [comment]
Fixed in version 0.9.0.
