### ISSUE TITLE
Reclaim storage space after deletion

### ISSUE THREAD

**Issue by dipakw** [akrylysov/pogreb#28]
Pogreb,

Is there any way to reclaim disk storage space after deletion of records?

**Comment by akrylysov** [comment]
Version 0.9.0 introduced compaction. The disk space occupied by overwritten or deleted keys can be reclaimed by calling [Compact](https://godoc.org/github.com/akrylysov/pogreb#DB.Compact) or by enabling [background compaction](https://godoc.org/github.com/akrylysov/pogreb#Options).
