### ISSUE TITLE
murmur hash functions fail on non-Windows machines due to unsafe pointers on go 1.14

### ISSUE THREAD

**Issue by maximinus** [akrylysov/pogreb#32]
The `Sum32WithSeed` function in /hash/murmur32.go fails with "checkptr: unsafe pointer arithmetic" from Go 1.14 onwards, due to the flag `-race` now being applied automatically.

This prevents pogreb from working on any non-Windows version running on Go 1.14

An example of more correct code can be found [here](https://github.com/twmb/murmur3/blob/master/murmur32_gen.go)

**Comment by akrylysov** [comment]
I'm planning fixing it soon, can you try upgrading to Go 1.14.1 as a workaround? The new Go version  made the `checkptr` less strict https://github.com/golang/go/issues/37905.

**Comment by akrylysov** [comment]
Thanks for the report, was fixed in version 0.9.1.
