### ISSUE TITLE
Memory mapping all segment files causes memory exhaustion

### ISSUE THREAD

**Issue by Kleissner** [akrylysov/pogreb#36]
We are storing billions of records using Pogreb. It creates many 4GB segment files (.PSG).
It is my understanding that those files represent the write-ahead log (WAL) which is only used in case of recover?

If that is indeed the case, then only the last WAL file needs to be open (for writing)?
Currently those files are literally exhausting our memory and use about 80 GB of RAM.

![image](https://user-images.githubusercontent.com/13511064/102474051-7807aa00-4058-11eb-992c-5f5fb16a33fa.png)

Using RamMap we found the culprit - memory mapped PSG files:
![image](https://user-images.githubusercontent.com/13511064/102474215-ac7b6600-4058-11eb-9cb3-d8821c715cac.png)

**Comment by akrylysov** [comment]
Pogreb stores keys and values in the write ahead log (which consists of `.psg` segment files). The index only contains pointers to the WAL.

Mmap maps the entire segment files into the process memory. It doesn't mean that the virtual memory is backed by physical RAM. Are you sure the numbers you are seeing is the residential memory?

The next Pogreb release will include a config option to not mmap the WAL.

**Comment by Kleissner** [comment]
Thanks for the clarification. It is not in residential memory, it's Windows doing all the allocation for the file mappings. The process itself is only reported to use 14 GB of RAM in Task Manager, but then the memory mapped files take up pretty much the rest of the RAM. I will see if it results in any problems when the database grows even further - there's still hundreds of millions records to be inserted.

It might be actually no problem if Windows is smart enough in loading the memory mapped files on demand (and deallocating unused parts when memory becomes sparse) - I will report back.
In any case having an option for disabling memory mapping would be great.

I want to use the chance to say a big thank you for this key-value database. We have tried out Badger, Bold and Bitcask, and yours is not only the fastest, it is also the most stable by far. Good work 👍🏻

**Comment by akrylysov** [comment]
Thanks a lot for the feedback! Version [0.10.0](https://github.com/akrylysov/pogreb/releases/tag/v0.10.0) now allows disabling memory-mapped file access by setting `Options.FileSystem` to `fs.OS`.
