### ISSUE TITLE
Failure to compile for x386 32 bit plaform

### ISSUE THREAD

**Issue by aydink** [akrylysov/pogreb#43]
I compile project for windows 64 bit or macOS 64 bit and it works fine.
When I set GOOS=windows and GOARCH=386, project fails to compile with the following error.

pogreb@v0.10.0\fs\os_mmap_windows.go:23:12: constant 2147483648 overflows int
pogreb@v0.10.0\fs\os_mmap_windows.go:23:12: array bound is too large

**Comment by akrylysov** [comment]
Thanks for the report. Fixed in https://github.com/akrylysov/pogreb/commit/8924c227b51d909a32226c4c69e03158ed038bc0
