### ISSUE TITLE
Need information on few points about pogreb

### ISSUE THREAD

**Issue by vishaljangid1729** [akrylysov/pogreb#50]
Hi Team

Need to know whether pogreb can support TB of data in the data store?
And retrieve more than 500k values for a specific hash key using prefix iteration?

Thanks
Vishal

**Comment by akrylysov** [comment]
Hi,

> Need to know whether pogreb can support TB of data in the data store?

Yes, it can support terabytes of data as long as the number of keys is less than 2 billion (see [MaxKeys](https://pkg.go.dev/github.com/akrylysov/pogreb#pkg-constants)).

> And retrieve more than 500k values for a specific hash key using prefix iteration?

Pogreb can't have more than a single value for the same key. Prefix iteration is also not supported, it can do only point lookups.
