### ISSUE TITLE
error reading segment meta 0

### ISSUE THREAD

**Issue by michail-vestnik** [akrylysov/pogreb#58]
hi!

Every time I restart, I get this error.

```sh
pogreb: error reading segment meta 0: EOF
```

what it means and how critical it is?

**Comment by akrylysov** [comment]
Hi!

Could you please provide an example that reproduces the issue?

**Comment by michail-vestnik** [comment]
this error occurs on the second and all subsequent starts. 

![Screenshot from 2023-08-06 12-57-37](https://github.com/akrylysov/pogreb/assets/87961969/0a5a0a9e-0b7d-417f-834a-8075b210b842)

on the screenshot you can see that this error is present in the logs of the second start.

**Comment by akrylysov** [comment]
You are getting these recovery log messages because the database wasn't closed properly. Add `db.Close()` at the end of `main` to solve this.

**Comment by michail-vestnik** [comment]
Yeah, I wanted to simulate a server crash. Even if you don't use **db.Close()** - the database is restored in full anyway?

**Comment by michail-vestnik** [comment]
Спасибо!
