### ISSUE TITLE
Are there any limitations to database size? (not max key amount)

### ISSUE THREAD

**Issue by m41denx** [akrylysov/pogreb#62]
Basically I want to store ~10TB. The current DB size is 340GB and growing by 150-170GB per day. The thing is i don't want it to die halfway.

So is there any db size limitations or is storing data as 4GB chunks allows it to scale indefinitely?

**Comment by akrylysov** [comment]
hi! There is limit on the number of segments - 32767, with the default max segment size of 4GiB it limits the total database size to ~131TiB. 

I'm curious, how many keys do you expect to store? Pogreb uses a 32 bit hash function, so as the number of keys gets close to the limit, the number of collisions increases and the performance degrades

**Comment by m41denx** [comment]
Hi! Glad to hear Pogreb can store that much data, I expect to store ~150mil keys at max, And sorry for the late response
