### ISSUE TITLE
DB is in an incorrect state after failed recovery

### ISSUE THREAD

**Issue by mcrakhman** [akrylysov/pogreb#63]
Hi! 

We encountered that our database cannot start with the following error `opening index: opening index meta: EOF`. This happened after our nodes continuously restarted for several times due to some panics in our code. These panics presumably happened when the DB tried to recover.

To reproduce this problem on a clean DB you can:
- open a DB, but not close it, this will make the `lock` file stay in the folder without a process having a lock on it.
- this will set `acquiredExistingLock` to true and all the index files would be renamed with the `.bac` in the end
- the DB will run `recover`, but if you **crash** the program before `clean = nil` in `pogreb.Open` this will make `main.pix` stay in the folder, but with `lock` file deleted due to `defer` being called
- therefore the next time you start this condition will be called `if err := idx.readMeta(); err != nil {`, where there will be no `index.pmt` file, thus we will create empty one in `readGobFile` only with header due to `f.writeHeader()`, but then will fail to decode `dec.Decode(v)`

Probably the solution will be to rebuild the indexes from scratch if there was a problem opening them, but probably you know better :-)

Btw the library is great and it is really fast for our purposes, so kudos to you for making it!

Thanks a lot!

**Comment by akrylysov** [comment]
hi!

> Btw the library is great and it is really fast for our purposes, so kudos to you for making it!

Thank you and thanks for the bug report!

> if err := idx.readMeta(); err != nil {, where there will be no index.pmt file, thus we will create empty one in readGobFile only with header due to f.writeHeader()

This is _a_ problem, I'm going to make `readMeta` open the file in a read-only mode. 

I'm still trying to wrap my head around of how the database could get into that state. The defer block and the cleanup code, which deletes the lock file should never run if the process crashes before `clean = nil`. Pogreb outputs its recovery logs to stderr, any chance you have still the logs from the server where you saw the crash?

Regardless of how this happened, I updated the code to keep the lock file around on all errors opening the DB, please take a look once you have a chance https://github.com/akrylysov/pogreb/compare/master...fix-recovery

**Comment by akrylysov** [comment]
I merged the fix, after you upgrade, please let me know if you see the issue again.

**Comment by mcrakhman** [comment]
Hi! Sorry for late reply, yes everything seems fine, can you please make an updated version of the library? And thanks a lot for the fix!

**Comment by akrylysov** [comment]
done! https://github.com/akrylysov/pogreb/releases/tag/v0.10.2
