### ISSUE TITLE
could you add whitedb connector for pogrep?

### ISSUE THREAD

**Issue by osevan** [akrylysov/pogreb#64]
Pogrep is really nice database solution,  but i know whitedb is the fastest in world but written in c language. 

https://github.com/priitj/whitedb

https://pkg.go.dev/cmd/cgo

Thx and 
Best regards

**Comment by akrylysov** [comment]
Hi, I'm not sure I fully understand the proposal. Could you please clarify if you are suggesting Pogreb to start relying on whitedb? It sounds like what you are looking for is a Go wrapper for whitedb. You can implement it using Cgo. I don't think Pogreb can help with it in any way.
