### ISSUE TITLE
High disk space occupation

### ISSUE THREAD

**Issue by brookxs** [akrylysov/pogreb#66]
For the same data, I only need 300m in size on bboltdb, but it takes up over 26GB of disk space on pogreb. I don't understand why this is?
I am using Bitmap data to store Roaring, and I am using it for inverted indexing. We will first check if the participle is in the aggregate, and then check if the document ID is in the bitmap. If it is not, we will add a new one. Then deposit it into the aggregate.
Here are some example codes。

``` go

func IndexDocuments(doc Document) error {
	var wg = sync.WaitGroup{}
	var err error
	for _, tk := range doc.TokenSlice {
		wg.Add(1)
		go func(tk string, err2 *error) {
			defer wg.Done()
			value, err := indexDB.Get([]byte(tk))
			if err != nil {
				*err2 = err
				return
			}
			if value == nil {
				rb := roaring.BitmapOf(doc.Id)
				data, err := rb.ToBytes()
				if err != nil {
					*err2 = err
					return
				}
				if err := indexDB.Put(utils.String2Bytes(tk), data); err != nil {
					*err2 = err
					return
				}
				return
			}
			rb, err := read(value)
			if err != nil {
				*err2 = err
				return
			}
			rb.Add(doc.Id)
			data, err := rb.ToBytes()
			if err != nil {
				*err2 = err
				return
			}
			if err := indexDB.Put(utils.String2Bytes(tk), data); err != nil {
				*err2 = err
				return
			}
		}(tk, &err)
	}
	wg.Wait()
	if err != nil {
		return err
	}
	return docDB.Put(utils.Uint2Bytes(doc.Id), utils.String2Bytes(doc.Word))
}
```

**Comment by akrylysov** [comment]
Hi!

I see the code above does "Read-Modify-Write" to update the search index. Pogreb doesn't reclaim space taken by overwritten or deleted keys automatically as described in the [design](https://github.com/akrylysov/pogreb/blob/main/docs/design.md#compaction) document. You either need to enable automatic compaction by setting [BackgroundCompactionInterval](https://pkg.go.dev/github.com/akrylysov/pogreb#Options) or run the compaction manually by calling [DB.Compact](https://pkg.go.dev/github.com/akrylysov/pogreb#DB.Compact).

**Comment by brookxs** [comment]
> Hi!
> 
> I see the code above uses a "Read-Modify-Write" loop to update the search index. Pogreb doesn't reclaim space taken by overwritten or deleted keys automatically as described in the [design](https://github.com/akrylysov/pogreb/blob/main/docs/design.md#compaction) document. You either need to enable automatic compaction by setting [BackgroundCompactionInterval](https://pkg.go.dev/github.com/akrylysov/pogreb#Options) or run the compaction manually by calling [DB.Compact](https://pkg.go.dev/github.com/akrylysov/pogreb#DB.Compact).

thanks
