### ISSUE TITLE
bad test freelist_test.go

### ISSUE THREAD

**Issue by kuerant** [akrylysov/pogreb#9]
$ go test -v -bench=.  -count 2

testing will panic in freelist_test.go.

To debug it, I modify some code :

func TestFreelistSerialization(t *testing.T) {
	l := freelist{[]block{{1, 1}, {2, 2}, {3, 3}, {10, 10}}}
	f, _ := openFile(fs.Mem, "test", 0, 0)

CHANGE TO :

func TestFreelistSerialization(t *testing.T) {
	l := freelist{[]block{{1, 1}, {2, 2}, {3, 3}, {10, 10}}}
	f, err := openFile(fs.Mem, "test", 0, 0)
        if err != nil {
           t.Fatal(err)
       }

openFile() fail :  freelist_test.go:130: file already exists

**Comment by akrylysov** [comment]
Thanks for the bug report, fixed in https://github.com/akrylysov/pogreb/commit/6535cdfbb484694cae7f283c73bbadc884dfc0dc
